### ISSUE TITLE
author page has disappeared, author links are no longer clickable

### ISSUE THREAD

**Issue by daxtens** [sthbrx/sthbrx-blog#4]
Much sadness. Very to fix.

**Comment by ajdlinux** [comment]
Hmm, any idea when this started happening? Did we have this working after the switch to Pelican?

**Comment by daxtens** [comment]
Yeah we did because I used it in my dockercon abstract submission. Happened between my last post and this rash of posts.

**Comment by ajdlinux** [comment]
Hmm, I'll take a look

**Comment by daxtens** [comment]
:tada: Thanks! :100:

**Comment by ajdlinux** [comment]
Can you point me to a commit where the author links are clickable?

**Comment by ajdlinux** [comment]
Also seems we don't have any pages that actually link to authors.html

**Comment by daxtens** [comment]
Huh, maybe I was wrong and I just figured out the URL myself.

In that case, we should make the author links clickable.

**Comment by daxtens** [comment]
The file I was actually looking for was /authors. We should also probs link to that somewhere.

**Comment by ajdlinux** [comment]
mpe has noticed the lack of author links on the posts. Let's see...

**Comment by CallumScar** [comment]
Hey guys I've had a look at the author page issue and it would appear the problem resides in the new posts that have been added since I left. the new posts have NOT been formatted correctly in markdown to function properly with our new blog SSG. ALL posts should follow this basic information format at the very beginning of each post.
Title:Authors:Date:Category:Tags:
Hope this helps to solve the issue. Make sure these changes are implemented to all recent posts. I reformatted the old posts. 
ThanksCallum Scarvell
PS with the general permission of the sthbrx authors I am happy to personally fix this issue on Github.
Date: Wed, 23 Mar 2016 18:37:38 -0700

**Comment by CallumScar** [comment]
Hello Again.Upon further inspection of the issue it would appear it is more complicated than previously thought. I have read over pelicans documentation regarding the generating of author content and the author page. It seems that it has somehow deleted the configuration settings (pelicanconf.py) set up by Chris and I and replaced it with the default. I am still unsure as to how this happened and how to prevent it happening again. Never the less here is the docs on the creation of Author URLs. hope it helps.
AUTHOR_URL = 'author/{slug}.html'The URL to use for an author.AUTHOR_SAVE_AS = 'author/{slug}.html'The location to save an author.YEAR_ARCHIVE_SAVE_AS = ''The location to save per-year archives of your posts.MONTH_ARCHIVE_SAVE_AS = ''The location to save per-month archives of your posts.DAY_ARCHIVE_SAVE_AS = ''The location to save per-day archives of your posts.SLUG_SUBSTITUTIONS = ()Substitutions to make prior to stripping out non-alphanumerics when generating slugs. Specified as a list of 2-tuples of (from, to)which are applied in order.NoteIf you do not want one or more of the default pages to be created (e.g., you are the only author on your site and thus do not need an Authors page), set the corresponding *_SAVE_AS setting to '' to prevent the relevant page from being generated.
And a link to the page; http://docs.getpelican.com/en/3.6.3/settings.html#paginationGoodluckCallum Scarvell
From: callum.s@live.com.au
To: reply@reply.github.com
Subject: RE: [sthbrx-blog] author page has disappeared, author links are no longer clickable (#4)
Date: Tue, 5 Apr 2016 23:33:46 +1030

Hey guys I've had a look at the author page issue and it would appear the problem resides in the new posts that have been added since I left. the new posts have NOT been formatted correctly in markdown to function properly with our new blog SSG. ALL posts should follow this basic information format at the very beginning of each post.
Title:Authors:Date:Category:Tags:
Hope this helps to solve the issue. Make sure these changes are implemented to all recent posts. I reformatted the old posts. 
ThanksCallum Scarvell
PS with the general permission of the sthbrx authors I am happy to personally fix this issue on Github.
Date: Wed, 23 Mar 2016 18:37:38 -0700

**Comment by ajdlinux** [comment]
Thanks for the pointers @CallumScar - it looks like in this case though we're actually generating all the right pages, we're just missing links. Hmmmmmmmmmm.

**Comment by ajdlinux** [comment]
Ah, it looks like if we don't have `AUTHOR_SAVE_AS` set in the config then it doesn't make the links clickable in our template. Fixing!

**Comment by CallumScar** [comment]
Ahh yes atom links can be tricky especially when generating multiple pages

Date: Mon, 18 Apr 2016 00:26:35 -0700
